# esto es un fichero yaml
version: "3"
services:
     phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - "8081:80"
      environment:
        PMA_HOST: basedatos
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: miclave

     basedatos:
       image: "mysql"
       container_name: "mimysql"
       environment:
          MYSQL_ROOT_PASSWORD : "miclave"
          MYSQL_DATABASE: "wordpress"
       expose:
          - "3306"
       networks:
          - "mired"
     wordpress:
       image: "wordpress"
       container_name: "miwordpress"
       environment:
         WORDPRESS_DB_HOST: "mimysql"
         WORDPRESS_DB_USER: "root"
         WORDPRESS_DB_PASSWORD: "miclave"
         WORDPRESS_DB_NAME: "wordpress"
       ports:
          - "8080:80"
       networks:
          - "mired"
       volumes:
         - mysql_data:/data
       depends_on:
          - basedatos
networks:
    mired:
volumes:
  mysql_data:


       